// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/kappctrl/v1alpha1"
	scheme "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PkgRepositoriesGetter has a method to return a PkgRepositoryInterface.
// A group's client should implement this interface.
type PkgRepositoriesGetter interface {
	PkgRepositories() PkgRepositoryInterface
}

// PkgRepositoryInterface has methods to work with PkgRepository resources.
type PkgRepositoryInterface interface {
	Create(ctx context.Context, pkgRepository *v1alpha1.PkgRepository, opts v1.CreateOptions) (*v1alpha1.PkgRepository, error)
	Update(ctx context.Context, pkgRepository *v1alpha1.PkgRepository, opts v1.UpdateOptions) (*v1alpha1.PkgRepository, error)
	UpdateStatus(ctx context.Context, pkgRepository *v1alpha1.PkgRepository, opts v1.UpdateOptions) (*v1alpha1.PkgRepository, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PkgRepository, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PkgRepositoryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PkgRepository, err error)
	PkgRepositoryExpansion
}

// pkgRepositories implements PkgRepositoryInterface
type pkgRepositories struct {
	client rest.Interface
}

// newPkgRepositories returns a PkgRepositories
func newPkgRepositories(c *KappctrlV1alpha1Client) *pkgRepositories {
	return &pkgRepositories{
		client: c.RESTClient(),
	}
}

// Get takes name of the pkgRepository, and returns the corresponding pkgRepository object, and an error if there is any.
func (c *pkgRepositories) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PkgRepository, err error) {
	result = &v1alpha1.PkgRepository{}
	err = c.client.Get().
		Resource("pkgrepositories").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PkgRepositories that match those selectors.
func (c *pkgRepositories) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PkgRepositoryList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PkgRepositoryList{}
	err = c.client.Get().
		Resource("pkgrepositories").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pkgRepositories.
func (c *pkgRepositories) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("pkgrepositories").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a pkgRepository and creates it.  Returns the server's representation of the pkgRepository, and an error, if there is any.
func (c *pkgRepositories) Create(ctx context.Context, pkgRepository *v1alpha1.PkgRepository, opts v1.CreateOptions) (result *v1alpha1.PkgRepository, err error) {
	result = &v1alpha1.PkgRepository{}
	err = c.client.Post().
		Resource("pkgrepositories").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pkgRepository).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a pkgRepository and updates it. Returns the server's representation of the pkgRepository, and an error, if there is any.
func (c *pkgRepositories) Update(ctx context.Context, pkgRepository *v1alpha1.PkgRepository, opts v1.UpdateOptions) (result *v1alpha1.PkgRepository, err error) {
	result = &v1alpha1.PkgRepository{}
	err = c.client.Put().
		Resource("pkgrepositories").
		Name(pkgRepository.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pkgRepository).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *pkgRepositories) UpdateStatus(ctx context.Context, pkgRepository *v1alpha1.PkgRepository, opts v1.UpdateOptions) (result *v1alpha1.PkgRepository, err error) {
	result = &v1alpha1.PkgRepository{}
	err = c.client.Put().
		Resource("pkgrepositories").
		Name(pkgRepository.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pkgRepository).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the pkgRepository and deletes it. Returns an error if one occurs.
func (c *pkgRepositories) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("pkgrepositories").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pkgRepositories) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("pkgrepositories").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched pkgRepository.
func (c *pkgRepositories) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PkgRepository, err error) {
	result = &v1alpha1.PkgRepository{}
	err = c.client.Patch(pt).
		Resource("pkgrepositories").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
