// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/packages/v1alpha1"
	scheme "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PkgsGetter has a method to return a PkgInterface.
// A group's client should implement this interface.
type PkgsGetter interface {
	Pkgs() PkgInterface
}

// PkgInterface has methods to work with Pkg resources.
type PkgInterface interface {
	Create(ctx context.Context, pkg *v1alpha1.Pkg, opts v1.CreateOptions) (*v1alpha1.Pkg, error)
	Update(ctx context.Context, pkg *v1alpha1.Pkg, opts v1.UpdateOptions) (*v1alpha1.Pkg, error)
	UpdateStatus(ctx context.Context, pkg *v1alpha1.Pkg, opts v1.UpdateOptions) (*v1alpha1.Pkg, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Pkg, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PkgList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Pkg, err error)
	PkgExpansion
}

// pkgs implements PkgInterface
type pkgs struct {
	client rest.Interface
}

// newPkgs returns a Pkgs
func newPkgs(c *PackagesV1alpha1Client) *pkgs {
	return &pkgs{
		client: c.RESTClient(),
	}
}

// Get takes name of the pkg, and returns the corresponding pkg object, and an error if there is any.
func (c *pkgs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Pkg, err error) {
	result = &v1alpha1.Pkg{}
	err = c.client.Get().
		Resource("pkgs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Pkgs that match those selectors.
func (c *pkgs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PkgList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PkgList{}
	err = c.client.Get().
		Resource("pkgs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pkgs.
func (c *pkgs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("pkgs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a pkg and creates it.  Returns the server's representation of the pkg, and an error, if there is any.
func (c *pkgs) Create(ctx context.Context, pkg *v1alpha1.Pkg, opts v1.CreateOptions) (result *v1alpha1.Pkg, err error) {
	result = &v1alpha1.Pkg{}
	err = c.client.Post().
		Resource("pkgs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pkg).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a pkg and updates it. Returns the server's representation of the pkg, and an error, if there is any.
func (c *pkgs) Update(ctx context.Context, pkg *v1alpha1.Pkg, opts v1.UpdateOptions) (result *v1alpha1.Pkg, err error) {
	result = &v1alpha1.Pkg{}
	err = c.client.Put().
		Resource("pkgs").
		Name(pkg.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pkg).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *pkgs) UpdateStatus(ctx context.Context, pkg *v1alpha1.Pkg, opts v1.UpdateOptions) (result *v1alpha1.Pkg, err error) {
	result = &v1alpha1.Pkg{}
	err = c.client.Put().
		Resource("pkgs").
		Name(pkg.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pkg).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the pkg and deletes it. Returns an error if one occurs.
func (c *pkgs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("pkgs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pkgs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("pkgs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched pkg.
func (c *pkgs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Pkg, err error) {
	result = &v1alpha1.Pkg{}
	err = c.client.Patch(pt).
		Resource("pkgs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
