// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/kappctrl/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePkgRepositories implements PkgRepositoryInterface
type FakePkgRepositories struct {
	Fake *FakeKappctrlV1alpha1
}

var pkgrepositoriesResource = schema.GroupVersionResource{Group: "kappctrl", Version: "v1alpha1", Resource: "pkgrepositories"}

var pkgrepositoriesKind = schema.GroupVersionKind{Group: "kappctrl", Version: "v1alpha1", Kind: "PkgRepository"}

// Get takes name of the pkgRepository, and returns the corresponding pkgRepository object, and an error if there is any.
func (c *FakePkgRepositories) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PkgRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(pkgrepositoriesResource, name), &v1alpha1.PkgRepository{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PkgRepository), err
}

// List takes label and field selectors, and returns the list of PkgRepositories that match those selectors.
func (c *FakePkgRepositories) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PkgRepositoryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(pkgrepositoriesResource, pkgrepositoriesKind, opts), &v1alpha1.PkgRepositoryList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PkgRepositoryList{ListMeta: obj.(*v1alpha1.PkgRepositoryList).ListMeta}
	for _, item := range obj.(*v1alpha1.PkgRepositoryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pkgRepositories.
func (c *FakePkgRepositories) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(pkgrepositoriesResource, opts))
}

// Create takes the representation of a pkgRepository and creates it.  Returns the server's representation of the pkgRepository, and an error, if there is any.
func (c *FakePkgRepositories) Create(ctx context.Context, pkgRepository *v1alpha1.PkgRepository, opts v1.CreateOptions) (result *v1alpha1.PkgRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(pkgrepositoriesResource, pkgRepository), &v1alpha1.PkgRepository{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PkgRepository), err
}

// Update takes the representation of a pkgRepository and updates it. Returns the server's representation of the pkgRepository, and an error, if there is any.
func (c *FakePkgRepositories) Update(ctx context.Context, pkgRepository *v1alpha1.PkgRepository, opts v1.UpdateOptions) (result *v1alpha1.PkgRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(pkgrepositoriesResource, pkgRepository), &v1alpha1.PkgRepository{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PkgRepository), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePkgRepositories) UpdateStatus(ctx context.Context, pkgRepository *v1alpha1.PkgRepository, opts v1.UpdateOptions) (*v1alpha1.PkgRepository, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(pkgrepositoriesResource, "status", pkgRepository), &v1alpha1.PkgRepository{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PkgRepository), err
}

// Delete takes name of the pkgRepository and deletes it. Returns an error if one occurs.
func (c *FakePkgRepositories) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(pkgrepositoriesResource, name), &v1alpha1.PkgRepository{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePkgRepositories) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(pkgrepositoriesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PkgRepositoryList{})
	return err
}

// Patch applies the patch and returns the patched pkgRepository.
func (c *FakePkgRepositories) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PkgRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(pkgrepositoriesResource, name, pt, data, subresources...), &v1alpha1.PkgRepository{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PkgRepository), err
}
