// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/clientset/versioned/typed/packages/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakePackagesV1alpha1 struct {
	*testing.Fake
}

func (c *FakePackagesV1alpha1) Pkgs() v1alpha1.PkgInterface {
	return &FakePkgs{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePackagesV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
